# Generated by Django 5.2.6 on 2025-10-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_lessonlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='title',
            field=models.CharField(default='Флэш-карты', max_length=200),
        ),
    ]
