# Generated by Django 5.2.6 on 2025-10-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_lesson_options_lesson_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='image',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/answers/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/questions/'),
        ),
    ]
